# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fd09ea83cba876bf6a94d996e29cc27b9ef9c8af3dbe0c5075b2dfaa043ee8c0cc9cf0a9c51e16661fddac02d04644e3f8bb6ef92fd26f224a31aa4fb5577bb

test:
  secret_key_base: e0f5bc253e9fafb9e095b41e9ae7adbc778661bd013fc592b3efed510f4edefe5c4dda67bb9f5396b5864a901fc36cdf48741c1192364f2897bc9e1699e59b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
